language: php

php:
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

install:
  - composer require satooshi/php-coveralls

script: 
  - mkdir -p build/logs
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
 
after_success:
  - travis_retry php vendor/bin/coveralls -v
