site_name: Greenter - Facturación Electrónica
site_url: https://giansalex.github.io/greenter
site_description: 'Facturación Electrónica Sunat - Perú'
site_author: 'Giancarlos Salas'

# Repository
repo_name: 'giansalex/greenter'
repo_url: 'https://github.com/giansalex/greenter'

pages:
    - Greenter: index.md
    - Primeros Pasos: starter.md
    - 'Documentación|https://giansalex.github.io/greenter-apidoc/': apidoc.md
    - News:
      - Start: news/index.md

# Configuration
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  logo:
    icon: 'receipt'
  language: 'es'
  feature:
    tabs: true
  palette:
    primary: 'Green'
    accent: 'Indigo'

extra_javascript:
  - js/ext_link.js

extra:
  social:
    - type: 'github'
      link: 'https://github.com/giansalex'
  author:
    github: giansalex
  disqus: 'greenter'

# Google Analytics
google_analytics:
  - 'UA-90097417-4'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
