site_name: Greenter - Facturación Electrónica en Perú
site_url: https://giansalex.github.io/greenter/
site_description: |
  Crea facturas electrónicas siguiendo el estándar UBL 2.0, 2.1 en Perú, 
  bajo la normativa dispuesta por SUNAT
site_author: 'Giancarlos Salas'

# Repository
repo_name: 'giansalex/greenter'
repo_url: 'https://github.com/giansalex/greenter'

copyright: Copyright &copy; 2017 Giancarlos Salas

nav:
    - Greenter: index.md
    - Primeros Pasos: starter.md
    - Migrar a UBL 2.1: migrate2.1.md
    - Paso a Producción: production.md
    - 'Preguntas Frecuentes': faq.md
    - 'API Referencia': https://giansalex.github.io/greenter-apidoc/
    - Ejemplos:
      - F. Exonerada: examples/exonerada.md
      - F. Gratuita: examples/gratuita.md
      - F. Descuentos: examples/descuento-linea.md
      - F. Percepción: examples/percepcion.md
      - F. Anticipos: examples/anticipo.md
      - F. Detracción: examples/detraccion.md
      - F. Exportación: examples/exportacion.md
      - F. ICBPER: examples/icbper.md
      - 'Boleta de Venta': examples/boleta.md
      - Contingencia: examples/contingencia.md

# Configuration
theme:
  name: 'material'
  custom_dir: docs/overrides
  favicon: 'img/greenter.ico'
  logo: 'img/logo.svg'
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  static_templates:
    - 404.html
  language: 'es'
  features:
    - tabs
  palette:
    primary: 'Green'
    accent: 'Indigo'

extra:
  manifest: 'manifest.json'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/giansalex
  disqus: 'greenter'

extra_css:
  - css/dark_theme.css
  - css/codehilite.css

# Google Analytics
google_analytics:
  - 'UA-90097417-4'
  - 'auto'

plugins:
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - pymdownx.mark
  - pymdownx.details
  - toc:
      permalink: true
